# --- start Python3 script --- #

# Information:
# auto-generated by sweetheart.services.WebappServer
# [ USER: nico ] [ DATE: Sun Nov  2 18:41:35 CET 2025 ]

# Import Sweetheart Services:
from sweetheart.services import *

# Set App Configuration:

config = set_config({
    # set here your own app config when required
    # but please refer to the documentation first
})

# Set Python Asgi/3 App for data:

# create here a runable entry point for your data traffic
# default and recommended is a PostgresUnchained data driver at the url /geldata
# NOTE: Sweetheart aims to serve statics directly via NginxUnit, not Asgi/3

webapp = WebappServer(config).app(
    # DataHub("/tsdata", TimescaleDB()), # NotImplemented
    DataHub("/geldata", PostgresUnchained()),
)

# --- end of script --- #